### ISSUE TITLE
Only showing 3 entries

### ISSUE THREAD

**Issue by 24khxn** [Nosskirneh/SpotifyHistory#1] opened 2018-01-19 16:00 UTC
I have a 6S running the Yalu pre-10.2 jailbreak. Although my option is set to infinite entries, the list keeps showing my 3 most recent listened to tracks. I LOVE this idea for a tweak, pls fix

**Comment by Nosskirneh** [comment] 2018-01-20 08:36
This sounds so strange. I'm unable to reproduce. Could you attach the file `/var/mobile/Library/Preferences/se.nosskirneh.spotifyhistory.plist`? Maybe that will give any clues.

**Comment by 24khxn** [comment] 2018-01-20 16:00
[infinite_selected.txt](https://github.com/Nosskirneh/SpotifyHistory/files/1648955/infinite_selected.txt)
[500_selected.txt](https://github.com/Nosskirneh/SpotifyHistory/files/1648956/500_selected.txt)

I couldn't attach the actual plist files so I just made them txt. The top link is when I have infinite selected, and the latter when I have 500. And after some playing around, I found out a better way to describe the problem. It's not that it's only showing 3 entries. I had it set to 500 entries for a couple days and so it built up a somewhat large list, but as soon as I go back to infinite entries, the list will not increase in size, but will add new songs to the top and remove old songs from the bottom. Thanks for the support man!

**Comment by Nosskirneh** [comment] 2018-01-22 07:27
txt is fine. The files still include large lists (more than three at least) and it should thus be showing more than three items.

I tried it out some more and it seems to be stuck at 414 tracks for me (set to infinity), and also crashes at selecting 30. I'll look into this when I get a little more time on my hands.

**Comment by Nosskirneh** [comment] 2018-02-08 20:18
Alright, should be fixed in https://github.com/Nosskirneh/SpotifyHistory/commit/246def2af0c9b8ea8b0b8bf7dbd8b90b4fc5609c. Will submit version 1.1 to BigBoss soon, feel free to reopen this if it doesn't work for you.

**Closed as completed by Nosskirneh** 2018-02-08 20:18 UTC
